import { AssetLoader } from "../../src/assets/AssetLoader";
import { MineRenderData } from "../../src/assets/MineRenderData";
import type { MineRenderDataManifest, MineRenderDatasets } from "../../src/assets/MineRenderData";

export const mineRenderDataFixtures: MineRenderDatasets = {
    itemDefaults: {
        "minecraft:diamond_pickaxe": {"minecraft:damage": 0, "minecraft:max_damage": 1561, "minecraft:max_stack_size": 1},
        "minecraft:compass": {"minecraft:max_stack_size": 64},
        "minecraft:clock": {"minecraft:max_stack_size": 64},
        "minecraft:written_book": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 16},
        "minecraft:end_crystal": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 64},
        "minecraft:debug_stick": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 1},
        "minecraft:apple": {"minecraft:max_stack_size": 64},
        "minecraft:book": {"minecraft:max_stack_size": 64},
        "minecraft:stone": {"minecraft:max_stack_size": 64},
        "minecraft:diamond_sword": {"minecraft:damage": 0, "minecraft:max_damage": 1561, "minecraft:max_stack_size": 1},
        "minecraft:iron_sword": {"minecraft:damage": 0, "minecraft:max_damage": 250, "minecraft:max_stack_size": 1},
        "minecraft:bow": {"minecraft:damage": 0, "minecraft:max_damage": 384, "minecraft:max_stack_size": 1},
        "minecraft:crossbow": {"minecraft:damage": 0, "minecraft:max_damage": 465, "minecraft:max_stack_size": 1},
        "minecraft:bundle": {"minecraft:max_stack_size": 1},
        "minecraft:elytra": {"minecraft:damage": 0, "minecraft:max_damage": 432, "minecraft:max_stack_size": 1},
        "minecraft:shield": {"minecraft:damage": 0, "minecraft:max_damage": 336, "minecraft:max_stack_size": 1},
        "minecraft:trident": {"minecraft:damage": 0, "minecraft:max_damage": 250, "minecraft:max_stack_size": 1},
        "minecraft:potion": {"minecraft:max_stack_size": 1},
        "minecraft:splash_potion": {"minecraft:max_stack_size": 1},
        "minecraft:lingering_potion": {"minecraft:max_stack_size": 1},
        "minecraft:enchanted_golden_apple": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 64},
        "minecraft:nether_star": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 64},
        "minecraft:snowball": {"minecraft:max_stack_size": 16},
        "minecraft:ender_pearl": {"minecraft:max_stack_size": 16},
        "minecraft:fishing_rod": {"minecraft:damage": 0, "minecraft:max_damage": 64, "minecraft:max_stack_size": 1},
        "minecraft:wolf_armor": {"minecraft:damage": 0, "minecraft:max_damage": 64, "minecraft:max_stack_size": 1},
        "minecraft:rabbit_hide": {"minecraft:max_stack_size": 64},
        "minecraft:oak_planks": {"minecraft:max_stack_size": 64},
        "minecraft:enchanted_book": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 1},
        "minecraft:experience_bottle": {"minecraft:enchantment_glint_override": true, "minecraft:max_stack_size": 64},
    },
    potionColors: {
        effects: {
            "minecraft:absorption": 2445989,
            "minecraft:bad_omen": 745784,
            "minecraft:blindness": 2039587,
            "minecraft:breath_of_the_nautilus": 65518,
            "minecraft:conduit_power": 1950417,
            "minecraft:darkness": 2696993,
            "minecraft:dolphins_grace": 8954814,
            "minecraft:fire_resistance": 16750848,
            "minecraft:glowing": 9740385,
            "minecraft:haste": 14270531,
            "minecraft:health_boost": 16284963,
            "minecraft:hero_of_the_village": 4521796,
            "minecraft:hunger": 5797459,
            "minecraft:infested": 9214860,
            "minecraft:instant_damage": 11101546,
            "minecraft:instant_health": 16262179,
            "minecraft:invisibility": 16185078,
            "minecraft:jump_boost": 16646020,
            "minecraft:levitation": 13565951,
            "minecraft:luck": 5882118,
            "minecraft:mining_fatigue": 4866583,
            "minecraft:nausea": 5578058,
            "minecraft:night_vision": 12779366,
            "minecraft:oozing": 10092451,
            "minecraft:poison": 8889187,
            "minecraft:raid_omen": 14565464,
            "minecraft:regeneration": 13458603,
            "minecraft:resistance": 9520880,
            "minecraft:saturation": 16262179,
            "minecraft:slow_falling": 15978425,
            "minecraft:slowness": 9154528,
            "minecraft:speed": 3402751,
            "minecraft:strength": 16762624,
            "minecraft:trial_omen": 1484454,
            "minecraft:unluck": 12624973,
            "minecraft:water_breathing": 10017472,
            "minecraft:weakness": 4738376,
            "minecraft:weaving": 7891290,
            "minecraft:wind_charged": 12438015,
            "minecraft:wither": 7561558,
        },
        potions: {
            "minecraft:awkward": [],
            "minecraft:fire_resistance": [{"amplifier": 0, "id": "minecraft:fire_resistance"}],
            "minecraft:harming": [{"amplifier": 0, "id": "minecraft:instant_damage"}],
            "minecraft:healing": [{"amplifier": 0, "id": "minecraft:instant_health"}],
            "minecraft:infested": [{"amplifier": 0, "id": "minecraft:infested"}],
            "minecraft:invisibility": [{"amplifier": 0, "id": "minecraft:invisibility"}],
            "minecraft:leaping": [{"amplifier": 0, "id": "minecraft:jump_boost"}],
            "minecraft:long_fire_resistance": [{"amplifier": 0, "id": "minecraft:fire_resistance"}],
            "minecraft:long_invisibility": [{"amplifier": 0, "id": "minecraft:invisibility"}],
            "minecraft:long_leaping": [{"amplifier": 0, "id": "minecraft:jump_boost"}],
            "minecraft:long_night_vision": [{"amplifier": 0, "id": "minecraft:night_vision"}],
            "minecraft:long_poison": [{"amplifier": 0, "id": "minecraft:poison"}],
            "minecraft:long_regeneration": [{"amplifier": 0, "id": "minecraft:regeneration"}],
            "minecraft:long_slow_falling": [{"amplifier": 0, "id": "minecraft:slow_falling"}],
            "minecraft:long_slowness": [{"amplifier": 0, "id": "minecraft:slowness"}],
            "minecraft:long_strength": [{"amplifier": 0, "id": "minecraft:strength"}],
            "minecraft:long_swiftness": [{"amplifier": 0, "id": "minecraft:speed"}],
            "minecraft:long_turtle_master": [{"amplifier": 3, "id": "minecraft:slowness"}, {"amplifier": 2, "id": "minecraft:resistance"}],
            "minecraft:long_water_breathing": [{"amplifier": 0, "id": "minecraft:water_breathing"}],
            "minecraft:long_weakness": [{"amplifier": 0, "id": "minecraft:weakness"}],
            "minecraft:luck": [{"amplifier": 0, "id": "minecraft:luck"}],
            "minecraft:mundane": [],
            "minecraft:night_vision": [{"amplifier": 0, "id": "minecraft:night_vision"}],
            "minecraft:oozing": [{"amplifier": 0, "id": "minecraft:oozing"}],
            "minecraft:poison": [{"amplifier": 0, "id": "minecraft:poison"}],
            "minecraft:regeneration": [{"amplifier": 0, "id": "minecraft:regeneration"}],
            "minecraft:slow_falling": [{"amplifier": 0, "id": "minecraft:slow_falling"}],
            "minecraft:slowness": [{"amplifier": 0, "id": "minecraft:slowness"}],
            "minecraft:strength": [{"amplifier": 0, "id": "minecraft:strength"}],
            "minecraft:strong_harming": [{"amplifier": 1, "id": "minecraft:instant_damage"}],
            "minecraft:strong_healing": [{"amplifier": 1, "id": "minecraft:instant_health"}],
            "minecraft:strong_leaping": [{"amplifier": 1, "id": "minecraft:jump_boost"}],
            "minecraft:strong_poison": [{"amplifier": 1, "id": "minecraft:poison"}],
            "minecraft:strong_regeneration": [{"amplifier": 1, "id": "minecraft:regeneration"}],
            "minecraft:strong_slowness": [{"amplifier": 3, "id": "minecraft:slowness"}],
            "minecraft:strong_strength": [{"amplifier": 1, "id": "minecraft:strength"}],
            "minecraft:strong_swiftness": [{"amplifier": 1, "id": "minecraft:speed"}],
            "minecraft:strong_turtle_master": [{"amplifier": 5, "id": "minecraft:slowness"}, {"amplifier": 3, "id": "minecraft:resistance"}],
            "minecraft:swiftness": [{"amplifier": 0, "id": "minecraft:speed"}],
            "minecraft:thick": [],
            "minecraft:turtle_master": [{"amplifier": 3, "id": "minecraft:slowness"}, {"amplifier": 2, "id": "minecraft:resistance"}],
            "minecraft:water": [],
            "minecraft:water_breathing": [{"amplifier": 0, "id": "minecraft:water_breathing"}],
            "minecraft:weakness": [{"amplifier": 0, "id": "minecraft:weakness"}],
            "minecraft:weaving": [{"amplifier": 0, "id": "minecraft:weaving"}],
            "minecraft:wind_charged": [{"amplifier": 0, "id": "minecraft:wind_charged"}],
        },
    },
    blockStates: {
        "minecraft:chest": {"facing": {"default": "north", "type": "enum", "valueType": "Direction", "values": ["north", "south", "west", "east"]}, "type": {"default": "single", "type": "enum", "valueType": "ChestType", "values": ["single", "left", "right"]}, "waterlogged": {"default": false, "type": "boolean", "valueType": "boolean", "values": [true, false]}},
        "minecraft:furnace": {"facing": {"default": "north", "type": "enum", "valueType": "Direction", "values": ["north", "south", "west", "east"]}, "lit": {"default": false, "type": "boolean", "valueType": "boolean", "values": [true, false]}},
        "minecraft:oak_log": {"axis": {"default": "y", "type": "enum", "valueType": "Axis", "values": ["x", "y", "z"]}},
        "minecraft:oak_slab": {"type": {"default": "bottom", "type": "enum", "valueType": "SlabType", "values": ["top", "bottom", "double"]}, "waterlogged": {"default": false, "type": "boolean", "valueType": "boolean", "values": [true, false]}},
        "minecraft:redstone_wire": {"east": {"default": "none", "type": "enum", "valueType": "RedstoneSide", "values": ["up", "side", "none"]}, "north": {"default": "none", "type": "enum", "valueType": "RedstoneSide", "values": ["up", "side", "none"]}, "power": {"default": 0, "type": "int", "valueType": "int", "values": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}, "south": {"default": "none", "type": "enum", "valueType": "RedstoneSide", "values": ["up", "side", "none"]}, "west": {"default": "none", "type": "enum", "valueType": "RedstoneSide", "values": ["up", "side", "none"]}},
        "minecraft:water": {"level": {"default": 0, "type": "int", "valueType": "int", "values": [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]}},
    },
    blockTints: {
        "minecraft:acacia_leaves": {"color": 4764952, "source": "constant"},
        "minecraft:attached_melon_stem": {"color": 14731036, "source": "constant"},
        "minecraft:attached_pumpkin_stem": {"color": 14731036, "source": "constant"},
        "minecraft:birch_leaves": {"color": 8431445, "source": "constant"},
        "minecraft:bush": {"source": "grass"},
        "minecraft:dark_oak_leaves": {"color": 4764952, "source": "constant"},
        "minecraft:fern": {"source": "grass"},
        "minecraft:grass_block": {"source": "grass"},
        "minecraft:jungle_leaves": {"color": 4764952, "source": "constant"},
        "minecraft:large_fern": {"source": "grass"},
        "minecraft:leaf_litter": {"color": 6044722, "source": "constant"},
        "minecraft:lily_pad": {"color": 7455580, "source": "constant"},
        "minecraft:mangrove_leaves": {"color": 4764952, "source": "constant"},
        "minecraft:melon_stem": {"source": "stem"},
        "minecraft:oak_leaves": {"color": 4764952, "source": "constant"},
        "minecraft:pink_petals": {"source": "grass", "untinted": [0]},
        "minecraft:potted_fern": {"source": "grass"},
        "minecraft:pumpkin_stem": {"source": "stem"},
        "minecraft:redstone_wire": {"source": "redstone"},
        "minecraft:short_grass": {"source": "grass"},
        "minecraft:spruce_leaves": {"color": 6396257, "source": "constant"},
        "minecraft:tall_grass": {"source": "grass"},
        "minecraft:vine": {"color": 4764952, "source": "constant"},
        "minecraft:water_cauldron": {"color": 4159204, "source": "constant"},
        "minecraft:wildflowers": {"source": "grass", "untinted": [0]},
    },
    fluids: {
        "minecraft:bubble_column": {"kind": "water", "renderModel": false},
        "minecraft:kelp": {"kind": "water", "renderModel": true},
        "minecraft:kelp_plant": {"kind": "water", "renderModel": true},
        "minecraft:lava": {"kind": "lava", "levelProperty": "level", "renderModel": false},
        "minecraft:seagrass": {"kind": "water", "renderModel": true},
        "minecraft:tall_seagrass": {"kind": "water", "renderModel": true},
        "minecraft:water": {"kind": "water", "levelProperty": "level", "renderModel": false},
    },
    dyes: {
        "black": {"fireworkColor": 1973019, "id": 15, "textColor": 0, "textureDiffuseColor": 1908001},
        "blue": {"fireworkColor": 2437522, "id": 11, "textColor": 255, "textureDiffuseColor": 3949738},
        "brown": {"fireworkColor": 5320730, "id": 12, "textColor": 9127187, "textureDiffuseColor": 8606770},
        "cyan": {"fireworkColor": 2651799, "id": 9, "textColor": 65535, "textureDiffuseColor": 1481884},
        "gray": {"fireworkColor": 4408131, "id": 7, "textColor": 8421504, "textureDiffuseColor": 4673362},
        "green": {"fireworkColor": 3887386, "id": 13, "textColor": 65280, "textureDiffuseColor": 6192150},
        "light_blue": {"fireworkColor": 6719955, "id": 3, "textColor": 10141901, "textureDiffuseColor": 3847130},
        "light_gray": {"fireworkColor": 11250603, "id": 8, "textColor": 13882323, "textureDiffuseColor": 10329495},
        "lime": {"fireworkColor": 4312372, "id": 5, "textColor": 12582656, "textureDiffuseColor": 8439583},
        "magenta": {"fireworkColor": 12801229, "id": 2, "textColor": 16711935, "textureDiffuseColor": 13061821},
        "orange": {"fireworkColor": 15435844, "id": 1, "textColor": 16738335, "textureDiffuseColor": 16351261},
        "pink": {"fireworkColor": 14188952, "id": 6, "textColor": 16738740, "textureDiffuseColor": 15961002},
        "purple": {"fireworkColor": 8073150, "id": 10, "textColor": 10494192, "textureDiffuseColor": 8991416},
        "red": {"fireworkColor": 11743532, "id": 14, "textColor": 16711680, "textureDiffuseColor": 11546150},
        "white": {"fireworkColor": 15790320, "id": 0, "textColor": 16777215, "textureDiffuseColor": 16383998},
        "yellow": {"fireworkColor": 14602026, "id": 4, "textColor": 16776960, "textureDiffuseColor": 16701501},
    },
    legacyBlocks: {
        blocks: {
            "0:0": "minecraft:air",
            "1:0": "minecraft:stone",
            "1:1": "minecraft:granite",
            "3:0": "minecraft:dirt",
            "17:4": "minecraft:oak_log[axis=x]",
            "35:0": "minecraft:white_wool",
            "35:14": "minecraft:red_wool",
            "54:2": "minecraft:chest[facing=north,type=single]",
            "255:0": "minecraft:structure_block[mode=save]",
            "31:1": "minecraft:short_grass",
            "208:0": "minecraft:dirt_path",
            "63:3": "minecraft:oak_sign[rotation=3]",
            "68:5": "minecraft:oak_wall_sign[facing=east]",
            "118:0": "minecraft:cauldron",
            "118:2": "minecraft:water_cauldron[level=2]",
            "132:0": "minecraft:tripwire[disarmed=false,east=false,powered=false,south=false,north=false,west=false,attached=false]",
            "132:2": "minecraft:tripwire[disarmed=false,east=false,powered=false,south=false,north=false,west=false,attached=false]",
            "132:1": "minecraft:tripwire[disarmed=false,east=false,powered=true,south=false,north=false,west=false,attached=false]",
            "132:3": "minecraft:tripwire[disarmed=false,east=false,powered=true,south=false,north=false,west=false,attached=false]",
            "132:4": "minecraft:tripwire[disarmed=false,east=false,powered=false,south=false,north=false,west=false,attached=true]",
            "132:6": "minecraft:tripwire[disarmed=false,east=false,powered=false,south=false,north=false,west=false,attached=true]",
            "132:5": "minecraft:tripwire[disarmed=false,east=false,powered=true,south=false,north=false,west=false,attached=true]",
            "132:7": "minecraft:tripwire[disarmed=false,east=false,powered=true,south=false,north=false,west=false,attached=true]",
            "132:8": "minecraft:tripwire[disarmed=true,east=false,powered=false,south=false,north=false,west=false,attached=false]",
            "132:10": "minecraft:tripwire[disarmed=true,east=false,powered=false,south=false,north=false,west=false,attached=false]",
            "132:9": "minecraft:tripwire[disarmed=true,east=false,powered=true,south=false,north=false,west=false,attached=false]",
            "132:11": "minecraft:tripwire[disarmed=true,east=false,powered=true,south=false,north=false,west=false,attached=false]",
            "132:12": "minecraft:tripwire[disarmed=true,east=false,powered=false,south=false,north=false,west=false,attached=true]",
            "132:14": "minecraft:tripwire[disarmed=true,east=false,powered=false,south=false,north=false,west=false,attached=true]",
            "132:13": "minecraft:tripwire[disarmed=true,east=false,powered=true,south=false,north=false,west=false,attached=true]",
            "132:15": "minecraft:tripwire[disarmed=true,east=false,powered=true,south=false,north=false,west=false,attached=true]",
        },
    },
};

export function mineRenderDataManifest(version = "1.21.11"): MineRenderDataManifest {
    const files = { itemDefaults: "item-defaults", potionColors: "potion-colors", blockStates: "block-states",
        blockTints: "block-tints", fluids: "fluids", dyes: "dyes", legacyBlocks: "legacy-blocks" };
    return {
        schemaVersion: 1, minecraftVersion: version, dataVersion: 4671,
        datasets: Object.fromEntries(Object.entries(files).map(([dataset, file]) => [dataset,
            { file: `${file}.json`, sha256: "0".repeat(64), bytes: 1, provenance: {} }])) as MineRenderDataManifest["datasets"],
        unavailable: {}, extractor: { repository: "test", revision: "test", sha256: "0".repeat(64) }
    };
}

export function installMineRenderDataFixtures(overrides: Partial<MineRenderDatasets> | ((root: string) => Partial<MineRenderDatasets>) = {}): () => void {
    const original = { get: MineRenderData.get, resolve: MineRenderData.resolve };
    MineRenderData.get = async (dataset, root = AssetLoader.ROOT) => {
        const values = typeof overrides === "function" ? overrides(root) : overrides;
        return (values[dataset] ?? mineRenderDataFixtures[dataset]) as any;
    };
    MineRenderData.resolve = async (root = AssetLoader.ROOT) => {
        const requestedVersion = root.slice(root.lastIndexOf("/") + 1);
        const version = /^\d+\.\d+(?:\.\d+)?$/.test(requestedVersion) ? requestedVersion : "1.21.11";
        return { requestedVersion, version, root, manifest: mineRenderDataManifest(version) };
    };
    return () => { MineRenderData.get = original.get; MineRenderData.resolve = original.resolve; };
}
