#!/bin/bash
#
# Regenerates the `index.ts` barrel in every src directory, bottom-up.
#
# The generated ./src/index.ts is the *shared* barrel: everything in it must work in both the
# browser and Node. Platform-specific code lives in ./src/env and is exported by the hand-written
# entry points (src/index.browser.ts, src/index.node.ts) instead - see EXCLUDED_DIRS below.

set -euo pipefail

# make sure we're in the root directory
if [ ! -f package.json ]; then
  echo "Please run this script from the root directory of the project"
  exit 1
fi

# Directories deliberately kept out of the shared barrel.
#   src/env - the per-platform EnvProviders. Exporting src/env/node from here would pull `canvas`,
#             `node-persist` and `image-size` into the browser build, which is exactly what the
#             Env seam exists to prevent.
EXCLUDED_DIRS=("./src/env")

# Files that are entry points rather than library modules, matched by basename.
EXCLUDED_FILES=("index.ts" "index.browser.ts" "index.node.ts")

is_excluded_dir() {
  local dir="$1" excluded
  for excluded in "${EXCLUDED_DIRS[@]}"; do
    if [ "$dir" = "$excluded" ] || [ "${dir#"$excluded"/}" != "$dir" ]; then
      return 0
    fi
  done
  return 1
}

is_excluded_file() {
  local name="$1" excluded
  for excluded in "${EXCLUDED_FILES[@]}"; do
    [ "$name" = "$excluded" ] && return 0
  done
  return 1
}

add_export() {
  local dir="$1" spec="$2"
  [ -f "$dir/index.ts" ] || echo "// autogenerated" > "$dir/index.ts"
  echo "export * from './$spec';" >> "$dir/index.ts"
}

# -depth visits children before their parent, so a directory's index.ts always exists by the time
# the parent looks for it. (The old top-down walk needed a second pass, which is what produced the
# duplicated top-level exports.)
find ./src -depth -type d -not -path "*/_*" -print0 | while IFS= read -r -d '' dir; do
  if is_excluded_dir "$dir"; then
    continue
  fi

  [ -f "$dir/index.ts" ] && rm "$dir/index.ts"

  # .ts files
  for file in "$dir"/*.ts; do
    if [ -e "$file" ] && ! is_excluded_file "$(basename -- "$file")"; then
      case "$file" in
        *.d.ts) continue ;;   # handled below
      esac
      add_export "$dir" "$(basename -- "${file%.ts}")"
    fi
  done

  # .d.ts files, but only when there is no matching .ts implementation
  for file in "$dir"/*.d.ts; do
    if [ -e "$file" ]; then
      withoutExt="${file%.d.ts}"
      if [ ! -f "$withoutExt.ts" ]; then
        add_export "$dir" "$(basename -- "$withoutExt")"
      fi
    fi
  done

  # subdirectories that produced a barrel of their own
  for subdir in "$dir"/*; do
    if [ -d "$subdir" ] && [ -f "$subdir/index.ts" ]; then
      add_export "$dir" "${subdir#"$dir"/}"
    fi
  done
done

echo "regenerated $(find ./src -name index.ts | wc -l) barrel(s)"
